[package]
name = "pvalve"
version = "0.1.0"
authors = ["Jordan Yelloz <jordan@yelloz.me>"]
edition = "2018"
license = "MIT"

[dependencies]
tokio = { version = "1", features = ["full"] }
governor = "0.3"
nonzero_ext = "0.2"
crossterm = "*"
bytes = "1.0"
futures-timer = "3.0"
pin-project-lite = "0.2"
anyhow = "1"
[dependencies.tokio-util]
version = "0.6"
features = ["compat", "codec"]
[dependencies.futures]
version = "0.3"
features = ["std", "async-await", "executor", "io-compat"]
[dependencies.tui]
version = "0.14"
features = ["crossterm"]
